### ISSUE TITLE
[YASQE] Icon for fullscreen editing of SPARQL queries disappeared - why? 

### ISSUE THREAD

**Issue by tomas-knap** [TriplyDB/Yasgui#152]
Based on the https://github.com/Triply-Dev/YASGUI.YASQE-deprecated/issues/139, the optional icon which increases the query editor's size to fullscreen was removed. 

What was the motivation behind removing that icon? 

What is the recommended way to replace that functionality? I know there is a way how to make the textarea expandable in the vertical direction, but is there a way to also expand horizontally? 

Thank you

**Comment by LaurensRietveld** [comment]
Full screen mode was always a bit bug-prune. It would work fine on a plain html page with little to no special styling. But including it on more complex pages could result in small z-index related issues such as the autocomplete widget not showing up, or other elements on the page overlapping with yasqe.
This was also problematic when using Yasqe together with Yasr, as some Yasr plugins are heavily styled and could result in z-index issues with full-screen mode as well.

As it was difficult making this experience bug-free, we decided to remove it.

Still, if you want similar behaviour to what was removed, you could configure yasqe via the `pluginButtons` (see https://github.com/TriplyDB/Yasgui/blob/master/packages/yasqe/src/index.ts#L987) option so that:
- You show an expand/collapse icon 
- Onclick you'd set the yasqe style to absolute, with top/bottom/right/left set to 0.
